# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Francisco/Desktop/LAB ANALOGICO/Exp3/EXP3_TECLADO/EXP3_TECLADO.srcs/sources_1/ip/MEM_SINE/MEM_SINE.xci
# IP: The module: 'MEM_SINE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Francisco/Desktop/LAB ANALOGICO/Exp3/EXP3_TECLADO/EXP3_TECLADO.srcs/sources_1/ip/MEM_SINE/MEM_SINE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MEM_SINE'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Francisco/Desktop/LAB ANALOGICO/Exp3/EXP3_TECLADO/EXP3_TECLADO.srcs/sources_1/ip/MEM_SINE/MEM_SINE.xci
# IP: The module: 'MEM_SINE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Francisco/Desktop/LAB ANALOGICO/Exp3/EXP3_TECLADO/EXP3_TECLADO.srcs/sources_1/ip/MEM_SINE/MEM_SINE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MEM_SINE'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
